//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAppLabENavigation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAppLabENavigation.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        public static string AgeEntry {
            get {
                return ResourceManager.GetString("AgeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string calc {
            get {
                return ResourceManager.GetString("calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        public static string Click_Me {
            get {
                return ResourceManager.GetString("Click Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Country.
        /// </summary>
        public static string CountryPicker {
            get {
                return ResourceManager.GetString("CountryPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Height in inches.
        /// </summary>
        public static string In_Height {
            get {
                return ResourceManager.GetString("In_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Weight in pounds.
        /// </summary>
        public static string In_Weight {
            get {
                return ResourceManager.GetString("In_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your BMI.
        /// </summary>
        public static string Out_Text {
            get {
                return ResourceManager.GetString("Out_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BMI Calculator.
        /// </summary>
        public static string TitleText_Bmi {
            get {
                return ResourceManager.GetString("TitleText_Bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Old Enough to Drink?.
        /// </summary>
        public static string TitleText_drink {
            get {
                return ResourceManager.GetString("TitleText_drink", resourceCulture);
            }
        }
    }
}
